### ISSUE TITLE
Create Testing Host/Demo App

### ISSUE THREAD

**Issue by aaronpearce** [aaronpearce/Harmony#1]
As we require the CloudKit entitlement to test, we'll need to create a test host app to provide the ability for testing of the library. 

This app could also be dual purpose as a demo application.

**Comment by AzSiAz** [comment]
Any news on a basic demo application ?
I remember seeing something on Mastodon for a Todo app 🤔

**Comment by aaronpearce** [comment]
@AzSiAz There is this demo app available: https://github.com/aaronpearce/HarmonyDemoApp

**Comment by aaronpearce** [comment]
Closing this as it will require a bit more thought for a testing app.
